# Generated by Django 5.2.5 on 2025-09-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='avaliacao_geral',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_vendido',
            field=models.IntegerField(default=0),
        ),
    ]
