# Generated by Django 5.2.5 on 2025-10-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_produto_categoria_carrinho_carrinho_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho_produto',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='cadastros.carrinho'),
        ),
    ]
