# Generated by Django 5.2.5 on 2025-11-07 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_carrinho_produto_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho_produto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.produto'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='avaliacao_geral',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Avaliação Geral'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_vendido',
            field=models.IntegerField(default=0, verbose_name='Quantidade Vendido'),
        ),
    ]
