# Generated by Django 5.2.5 on 2026-01-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_carrinho_produto_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=18)),
                ('email', models.EmailField(help_text='E-mail inválido', max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=14)),
                ('data_cadastro', models.DateTimeField(auto_now=True, verbose_name='cadastrado em')),
                ('status', models.CharField(default='ativo', max_length=50)),
                ('descricao_loja', models.CharField(max_length=100)),
                ('imagem_logo', models.FileField(upload_to='pdf/')),
                ('endereco', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
