# Generated by Django 5.2.5 on 2026-01-04 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_camelo_produto_fornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='camelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastros.camelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='camelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastros.camelo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Total')),
                ('data_hora_mensagem', models.DateTimeField(auto_now=True, verbose_name='data do pedido')),
                ('mensagem', models.CharField(default='em andamento', max_length=30)),
                ('camelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.camelo')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Total')),
                ('data_pedido', models.DateTimeField(auto_now=True, verbose_name='data do pedido')),
                ('status', models.CharField(default='em andamento', max_length=30)),
                ('camelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.camelo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Camelo_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='cadastros.camelo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('camelo', 'usuario'), name='unique_camelo_usuario')],
            },
        ),
        migrations.CreateModel(
            name='Pedido_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('quantidade', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='cadastros.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pedido', 'produto'), name='unique_pedido_produto')],
            },
        ),
    ]
