# Generated by Django 5.2.5 on 2026-01-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_categoria_camelo_produto_camelo_avaliacao_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camelo',
            name='email',
            field=models.EmailField(help_text='Insira E-mail para contato', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='camelo',
            name='telefone',
            field=models.CharField(max_length=16),
        ),
    ]
