# Generated by Django 5.2.5 on 2026-01-05 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_camelo_email_alter_camelo_telefone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='camelo',
            name='usuarios',
            field=models.ManyToManyField(related_name='camelos', through='cadastros.Camelo_Usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='camelo_usuario',
            name='camelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_usuarios', to='cadastros.camelo'),
        ),
    ]
