# Generated by Django 5.2.5 on 2026-02-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_camelo_usuarios_alter_camelo_usuario_camelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='camelo',
        ),
    ]
