# Generated by Django 5.2.5 on 2026-03-05 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_remove_pedido_camelo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data_hora_mensagem',
            field=models.DateTimeField(auto_now=True, verbose_name='data e hora da avaliação'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='mensagem',
            field=models.CharField(default='mensagem da avalição', max_length=255),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
