# Generated by Django 5.2.5 on 2026-03-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='mensagem',
            field=models.CharField(max_length=255, verbose_name='mensagem da avalição'),
        ),
    ]
