# Generated by Django 5.2.5 on 2026-03-17 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_alter_avaliacao_mensagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camelo',
            name='endereco',
        ),
        migrations.AddField(
            model_name='camelo',
            name='bairro',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camelo',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camelo',
            name='cidade',
            field=models.CharField(default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camelo',
            name='complemento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='camelo',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='NA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camelo',
            name='logradouro',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camelo',
            name='numero',
            field=models.IntegerField(default='00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(max_length=150, null=True, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='opcao_pedido',
            field=models.CharField(default='receber em casa', max_length=30),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
