# Generated by Django 5.2.5 on 2026-03-25 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_remove_camelo_endereco_camelo_bairro_camelo_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='cadastros.produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='opcao_pedido',
            field=models.CharField(choices=[('casa', 'Receber em casa'), ('loja', 'Buscar na loja')], default='Receber em casa', max_length=30),
        ),
    ]
