# Generated by Django 5.2.5 on 2026-04-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_alter_avaliacao_produto_alter_pedido_opcao_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_produto',
            name='status',
            field=models.CharField(default='em andamento', max_length=30),
        ),
    ]
