# Generated by Django 5.2.5 on 2026-04-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_pedido_produto_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
    ]
