# Generated by Django 5.2.5 on 2026-04-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_remove_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='camelo',
            name='avaliacao_geral',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Avaliação Geral'),
        ),
    ]
