# Generated by Django 5.2.5 on 2026-04-10 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_camelo_avaliacao_geral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='camelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_camelo', to='cadastros.camelo'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_produto', to='cadastros.produto'),
        ),
    ]
