# Generated by Django 5.2.5 on 2025-09-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='complemento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.CharField(default='NA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(default='NA', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(default='NA', max_length=14, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(default='NA', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(default='NA', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(default='cliente', max_length=30),
        ),
    ]
