# Generated by Django 5.2.5 on 2026-02-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_cadastropendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropendente',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastropendente',
            name='senha',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
