# Generated by Django 5.2.5 on 2026-02-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_cadastropendente_email_cadastropendente_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastropendente',
            name='usuario',
        ),
    ]
