# Generated by Django 5.2.5 on 2026-02-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_cadastropendente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropendente',
            name='codigo_sms',
            field=models.CharField(default=123456, max_length=6),
            preserve_default=False,
        ),
    ]
